CREATE TABLE MachineDesign (
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(255) NOT NULL,
	DrawingCode NVARCHAR(30) NOT NULL,
	Client NVARCHAR(255) NOT NULL,
);

CREATE TABLE JobTask (
	Id INT PRIMARY KEY IDENTITY(1,1),
	Title NVARCHAR(255) NOT NULL,
	Owner NVARCHAR(30) NOT NULL,
	Status NVARCHAR(255) NOT NULL,
);